# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'
    - run: npm ci
    - name: 'Create env file'
      run: |
        touch .env
        echo DEFAULT_NETWORK="mainnet" >> .env
        echo PORT=3000 >> .env
        echo JSON_RPC_MAINNET=${{ secrets.JSON_RPC_MAINNET }} >> .env
        echo JSON_RPC_TESTNET=${{ secrets.JSON_RPC_TESTNET }} >> .env
        echo MNEMONIC=${{ secrets.MNEMONIC }} >> .env
    - run: npx hardhat compile
    - run: npm run build --if-present
